/**
 * FlowForge API Code Generator
 *
 * Converts a ForgeGraph into Express 5 route handler source code.
 * Each intent ("list Students", "create Student") maps to a CRUD handler
 * with built-in Zod validation, error handling, and role guards.
 */

import type { ForgeGraph, ResolvedRoute } from "../dsl/types.js";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toRouterPath(path: string): string {
    // Convert :entityId shorthand to Express param syntax
    return path.replace(/{(\w+)}/g, ":$1");
}

function routerVarName(path: string): string {
    const clean = path.replace(/^\//, "").replace(/[/:{}]/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");
    return clean || "root";
}

const CRUD_TEMPLATES: Record<string, (route: ResolvedRoute) => string> = {
    list: (r) => `
  /**
   * GET ${r.path}
   * Intent: "${r.intent}"
   */
  router.get("${toRouterPath(r.path)}", ${roleGuard(r)}async (req, res) => {
    try {
      const items = await db.query.${r.entity?.toLowerCase() ?? "items"}.findMany({
        orderBy: (t, { desc }) => [desc(t.createdAt)],
      });
      res.json({ data: items, count: items.length });
    } catch (err) {
      next(err);
    }
  });`,

    create: (r) => `
  /**
   * POST ${r.path}
   * Intent: "${r.intent}"
   */
  router.post("${toRouterPath(r.path)}", ${roleGuard(r)}async (req, res, next) => {
    try {
      const body = ${r.entity}InsertSchema.parse(req.body);
      const [item] = await db.insert(schema.${r.entity?.toLowerCase() ?? "items"}).values(body).returning();
      res.status(201).json({ data: item });
    } catch (err) {
      next(err);
    }
  });`,

    get: (r) => `
  /**
   * GET ${r.path}
   * Intent: "${r.intent}"
   */
  router.get("${toRouterPath(r.path)}", ${roleGuard(r)}async (req, res, next) => {
    try {
      const { id } = req.params;
      const item = await db.query.${r.entity?.toLowerCase() ?? "item"}.findFirst({
        where: (t, { eq }) => eq(t.id, id),
      });
      if (!item) return res.status(404).json({ error: "${r.entity} not found" });
      res.json({ data: item });
    } catch (err) {
      next(err);
    }
  });`,

    update: (r) => `
  /**
   * PATCH ${r.path}
   * Intent: "${r.intent}"
   */
  router.patch("${toRouterPath(r.path)}", ${roleGuard(r)}async (req, res, next) => {
    try {
      const { id } = req.params;
      const body = ${r.entity}InsertSchema.partial().parse(req.body);
      const [item] = await db.update(schema.${r.entity?.toLowerCase() ?? "item"})
        .set({ ...body, updatedAt: new Date() })
        .where(eq(schema.${r.entity?.toLowerCase() ?? "item"}.id, id))
        .returning();
      if (!item) return res.status(404).json({ error: "${r.entity} not found" });
      res.json({ data: item });
    } catch (err) {
      next(err);
    }
  });`,

    delete: (r) => `
  /**
   * DELETE ${r.path}
   * Intent: "${r.intent}"
   */
  router.delete("${toRouterPath(r.path)}", ${roleGuard(r)}async (req, res, next) => {
    try {
      const { id } = req.params;
      await db.delete(schema.${r.entity?.toLowerCase() ?? "item"}).where(eq(schema.${r.entity?.toLowerCase() ?? "item"}.id, id));
      res.status(204).send();
    } catch (err) {
      next(err);
    }
  });`,

    custom: (r) => `
  /**
   * ${r.method.toUpperCase()} ${r.path}
   * Intent: "${r.intent}" (custom — implement manually)
   */
  router.${r.method}("${toRouterPath(r.path)}", ${roleGuard(r)}async (req, res, next) => {
    // TODO: implement custom intent: "${r.intent}"
    res.status(501).json({ error: "Not implemented", intent: "${r.intent}" });
  });`,
};

function roleGuard(route: ResolvedRoute): string {
    if (!route.roles?.length) return "";
    const roles = route.roles.map((r) => `"${r}"`).join(", ");
    return `requireRoles([${roles}]), `;
}

// ─── Main Generator ──────────────────────────────────────────────────────────

/**
 * Generate the full Express router source from a ForgeGraph.
 * Returns a TypeScript source string to be written to a file.
 */
export function generateApi(graph: ForgeGraph): string {
    // Group routes by path prefix for subrouters
    const routesByPath = new Map<string, ResolvedRoute[]>();
    for (const route of graph.routes) {
        const key = route.path;
        if (!routesByPath.has(key)) routesByPath.set(key, []);
        routesByPath.get(key)!.push(route);
    }

    // Import section
    const entityInsertImports = [...new Set(
        graph.routes
            .filter((r) => r.entity)
            .map((r) => `${r.entity}InsertSchema`)
    )].join(", ");

    const imports = `/**
 * AUTO-GENERATED by FlowForge — DO NOT EDIT MANUALLY
 * App: ${graph.app} v${graph.version}
 * Generated at: ${new Date().toISOString()}
 *
 * To regenerate: forge generate <your-spec>.forge.yaml
 */

import { Router } from "express";
import { eq } from "drizzle-orm";
import { db, schema } from "@workspace/db";${entityInsertImports
            ? `\nimport { ${entityInsertImports} } from "@workspace/api-zod";`
            : ""
        }
${graph.auth.strategy !== "none" ? 'import { requireRoles } from "../middleware/auth.js";' : ""}
`;

    // Route handler bodies
    const routeBlocks: string[] = [];
    for (const route of graph.routes) {
        const template = CRUD_TEMPLATES[route.action] ?? CRUD_TEMPLATES.custom!;
        routeBlocks.push(template(route));
    }

    // Top-level router export
    const routerCode = `
const router = Router();
${routeBlocks.join("\n")}
export default router;
`;

    // Summary comment at bottom
    const summary = `
/*
 * FlowForge Generated Route Summary for "${graph.app}":
${graph.routes.map((r) => ` *   ${r.method.toUpperCase().padEnd(7)} ${r.path.padEnd(40)} → ${r.intent}`).join("\n")}
 */
`;

    return [imports, routerCode, summary].join("\n");
}
