/**
 * FlowForge Database Schema Generator
 *
 * Converts a ForgeGraph's entities into Drizzle ORM table definitions.
 * Generates: table declarations, drizzle-zod insert schemas, and a DB barrel export.
 */

import type { ForgeGraph, ResolvedEntity, ForgeField, ForgeScalar } from "../dsl/types.js";

// ─── Type Mappings ────────────────────────────────────────────────────────────

const SCALAR_TO_DRIZZLE: Record<ForgeScalar, string> = {
    string: "varchar(255)",
    text: "text",
    number: "numeric",
    boolean: "boolean",
    date: "date",
    datetime: "timestamp",
    email: "varchar(255)",
    url: "varchar(2048)",
    uuid: "uuid",
    json: "jsonb",
};

const SCALAR_TO_TS: Record<ForgeScalar, string> = {
    string: "string",
    text: "string",
    number: "number",
    boolean: "boolean",
    date: "Date",
    datetime: "Date",
    email: "string",
    url: "string",
    uuid: "string",
    json: "unknown",
};

// ─── Column generator ─────────────────────────────────────────────────────────

function generateColumn(name: string, field: ForgeField): string {
    const drizzleType = SCALAR_TO_DRIZZLE[field.type] ?? "text";
    const tsComment = `/** ${field.label ?? name} — ${SCALAR_TO_TS[field.type]} */`;

    let col = `  ${tsComment}\n  ${name}: `;

    // Map DrizzleType to Drizzle helper call
    if (field.type === "uuid") {
        col += field.name === "id"
            ? `uuid("${name}").primaryKey().defaultRandom()`
            : `uuid("${name}")`;
    } else if (field.type === "boolean") {
        col += `boolean("${name}")`;
        if (field.default !== undefined) col += `.default(${field.default})`;
    } else if (field.type === "datetime") {
        col += `timestamp("${name}", { withTimezone: true })`;
        if (field.default === "now") col += `.defaultNow()`;
    } else if (field.type === "date") {
        col += `date("${name}")`;
    } else if (field.type === "number") {
        col += `numeric("${name}")`;
        if (field.default !== undefined) col += `.default("${field.default}")`;
    } else if (field.type === "json") {
        col += `jsonb("${name}")`;
    } else {
        // string, text, email, url → use text or varchar
        const drizzleFn = field.type === "text" ? "text" : "varchar";
        const len = field.maxLength ?? (field.type !== "text" ? 255 : undefined);
        col += len ? `${drizzleFn}("${name}", { length: ${len} })` : `${drizzleFn}("${name}")`;
        if (field.default !== undefined) col += `.default("${field.default}")`;
    }

    if (field.unique) col += `.unique()`;
    if (!field.required) col += `.notNull(false)`;
    else if (field.type !== "uuid" || name !== "id") col += `.notNull()`;

    // Foreign key reference
    if (field.ref) {
        col += `\n    .references(() => ${field.ref.toLowerCase()}Table.id, { onDelete: "cascade" })`;
    }

    return col;
}

// ─── Entity table generator ───────────────────────────────────────────────────

function generateEntityTable(entity: ResolvedEntity): string {
    const tableName = `${entity.name.toLowerCase()}s`;
    const varName = `${entity.name.toLowerCase()}Table`;

    const columns: string[] = [
        `  /** Primary key */\n  id: uuid("id").primaryKey().defaultRandom()`,
    ];

    for (const [name, field] of Object.entries(entity.fields)) {
        columns.push(generateColumn(name, { ...field, name } as ForgeField & { name: string }));
    }

    if (entity.timestamps) {
        columns.push(`  /** Auto-managed timestamps */\n  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull()`);
        columns.push(`  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull()`);
    }

    if (entity.softDelete) {
        columns.push(`  /** Soft delete */\n  deletedAt: timestamp("deleted_at", { withTimezone: true })`);
    }

    const insertSchemaName = `${entity.name}InsertSchema`;
    const selectSchemaName = `${entity.name}Schema`;

    return `
/**
 * ${entity.name} (${entity.plural})
 * Auto-generated by FlowForge from intent spec.
 */
export const ${varName} = pgTable("${tableName}", {
${columns.join(",\n")},
});

export const ${insertSchemaName} = createInsertSchema(${varName});
export const ${selectSchemaName} = createSelectSchema(${varName});
export type ${entity.name} = typeof ${varName}.$inferSelect;
export type New${entity.name} = typeof ${varName}.$inferInsert;
`;
}

// ─── Barrel export generator ─────────────────────────────────────────────────

function generateBarrel(graph: ForgeGraph): string {
    const entityNames = Object.keys(graph.entities);
    return entityNames.map((e) => `export * from "./${e.toLowerCase()}.js";`).join("\n");
}

// ─── Main Generator ──────────────────────────────────────────────────────────

/**
 * Generate Drizzle ORM schema files from a ForgeGraph.
 * Returns a map of filename → source code strings.
 */
export function generateDb(graph: ForgeGraph): Map<string, string> {
    const files = new Map<string, string>();

    const header = `/**
 * AUTO-GENERATED by FlowForge — DO NOT EDIT MANUALLY
 * App: ${graph.app} v${graph.version}
 * Generated at: ${new Date().toISOString()}
 */

import { pgTable, uuid, varchar, text, numeric, boolean, date, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
`;

    // One file per entity
    for (const entity of Object.values(graph.entities)) {
        const src = header + generateEntityTable(entity);
        files.set(`schema/${entity.name.toLowerCase()}.ts`, src);
    }

    // Barrel file
    files.set("schema/index.ts", `// AUTO-GENERATED by FlowForge\n${generateBarrel(graph)}`);

    return files;
}
